### PR TITLE
update to search API

### PR DESCRIPTION
**Pull request by ajschumacher**
(use the right end point)

### CODE REVIEW

**Comment by fastfrwrd** [comment]
+1 - this change works for me.

**Comment by ajschumacher** [comment]
@fastfrwrd recommend switching to https://github.com/ttezel/twit - this project seems fairly abandoned

**Comment by kof** [comment]
@AvianFlu can you merge this change please and publish it?

**Comment by dfliess** [comment]
+1

**Comment by ajschumacher** [comment]
@jdub ping

**Comment by ajschumacher** [comment]
@jdub ping ping

**Comment by ajschumacher** [comment]
This project seems quite dead, and I don't want the PR cluttering up my list of open PRs. @jdub you can find it if ever you want!

**Pull request closed without merging**
