### PR TITLE
Fix for looking up multiple users.

### PR DESCRIPTION
**Pull request by clintandrewhall**
https://github.com/ciaranj/node-oauth/pull/7

Appears to have been fixed. My test oracle for my proposed fix:

```
    twitter.lookupUsers("rem", function(error, result) {
      if(error) {
        logger.error("Error in single string.");
        return logger.error(error);
      }
      return logger.info(result);
    });

    twitter.lookupUsers("rem, sh1mmer, mikeal", function(error, result) {
      if(error) {
        logger.error("Error in comma'd string.");
        return logger.error(error);
      }
      return logger.info(result);
    });

    twitter.lookupUsers("648873, sh1mmer, mikeal", function(error, result) {
      if(error) {
        logger.error("Error in comma'd string.");
        return logger.error(error);
      }
      return logger.info(result);
    });

    twitter.lookupUsers("63803", function(error, result) {
      if(error) {
        logger.error("Error in single string.");
        return logger.error(error);
      }
      return logger.info(result);
    });

    twitter.lookupUsers("63803 , 648873 , 668423", function(error, result) {
      if(error) {
        logger.error("Error in comma'd string.");
        return logger.error(error);
      }
      return logger.info(result);
    });

    twitter.lookupUsers("63803,648873,668423", function(error, result) {
      if(error) {
        logger.error("Error in comma'd string.");
        return logger.error(error);
      }
      return logger.info(result);
    });

    twitter.lookupUsers(["63803", "648873", "668423"], function(error, result) {
      if(error) {
        logger.error("Error in string array.");
        return logger.error(error);
      }
      return logger.info(result);
    });

    twitter.lookupUsers(63803, function(error, result) {
      if(error) {
        logger.error("Error in single number.");
        return logger.error(error);
      }
      return logger.info(result);
    });

    twitter.lookupUsers([63803, 648873, 668423], function(error, result) {
      if(error) {
        logger.error("Error in number array.");
        return logger.error(error);
      }
      return logger.info(result);
    });
```

Appears to work.

Basically, since the lookup will take user id and names, this _new_ logic will split everything up into the appropriate params.

### CODE REVIEW

**Comment by clintandrewhall** [comment]
Never underestimate a fresh pair of eyes, nor their ability to show up _after_ you've opened a pull request. :-)

If this works for you, when might this change make it to npm?

**Comment by AvianFlu** [comment]
I'll bump the version and publish it presently.  Thanks again!

**Comment by clintandrewhall** [comment]
Anytime! Glad I could help!

**Comment by AvianFlu** [comment]
`ntwitter@0.2.3` has been published.

**Pull request merged**
