### PR TITLE
Added updateProfileImg method

### PR DESCRIPTION
**Pull request by MRdNk**
Added updateProfileImg method - can update the profile image.

### CODE REVIEW

**Comment by MRdNk** [comment]
Any chance of getting this in and on npm, as I'm using it on a Hack Night project.

**Comment by AvianFlu** [comment]
Landed, thanks.

**Comment by MRdNk** [comment]
Thanks nice one, any idea when this'll be npm'able (made up word).

**Comment by AvianFlu** [comment]
About five minutes ago!

I released it as `ntwitter@0.4.0` because of the API additions.

**Comment by MRdNk** [comment]
Excellent thank you, looking forward to updating my package.json and getting people to pull it at the next hack night.
- mrdnk

**Pull request closed without merging**
